---
- name: Configure the PAN system attributes
  hosts: panos
  connection: local
  gather_facts: False
  tasks:
    - name: wait for SSH prompt (timeout 10min)
      wait_for:
        port: 22
        host: "{{ ansible_host }}"
        timeout: 600

    - name: configure ethernet1/1 for DHCP
      panos_interface:
        ip_address: "{{ ansible_host }}"
        password: "{{ network_password }}"
        if_name: "ethernet1/1"
        zone_name: "untrust"
        create_default_route: "yes"
        commit: False

    - name: configure ethernet1/2 for DHCP
      panos_interface:
        ip_address: "{{ ansible_host }}"
        password: "{{ network_password }}"
        if_name: "ethernet1/2"
        zone_name: "trust"
        create_default_route: "no"
        commit: False

    - name: Commit the configuration
      panos_commit:
        ip_address: "{{ ansible_host }}"
        password: "{{ network_password }}"
