---
- name: Configure the F5s
  hosts: tmos
  connection: local
  gather_facts: False
  tasks:

    - name: wait for SSH prompt (timeout 10min)
      wait_for:
        port: 22
        host: "{{ ansible_host }}"
        timeout: 600

    - name: Find a private key to use
      set_fact:
        ssh_private_key: "{{ item }}"
      with_first_found:
        - files:
          - "{{ ansible_ssh_private_key_file }}"
          - "../{{ ansible_ssh_private_key_file }}"
          - '~/.ssh/id_rsa'
          - '~/.ssh/id_dsa'

    # Changing admin password
    - name: Set the BigIP admin password
      expect:
        command: ssh -i "{{ ssh_private_key }}" -o StrictHostKeyChecking=no admin@"{{ ansible_host }}" modify auth password admin ; save sys config
        responses:
          (?i)password: "{{ network_password }}"
