---
- name: Configure the F5s
  hosts: tmos
  connection: local
  gather_facts: False
  vars:
    pool_name: http-pool
    pool_partition: Common
    vs_name: "{{ pool_name }}"
    vs_port: 80

  tasks:
    - name: Create the pool {{ pool_name }}
      bigip_pool:
        server: "{{ ansible_host }}"
        user: "{{ network_username }}"
        password: "{{ network_password }}"
        validate_certs: no
        name: "{{ pool_name }}"

    - name: Add a new node
      bigip_node:
        server: "{{ ansible_host }}"
        user: "{{ network_username }}"
        password: "{{ network_password }}"
        validate_certs: no
        state: "present"
        partition: "{{ pool_partition }}"
        host: "{{ hostvars[item].private_ip_address }}"
        name: "{{ item }}"
      when: groups.app_hosts is defined
      with_items: "{{ groups.app_hosts }}"

    - name: Add host to pool member
      bigip_pool_member:
        server: "{{ ansible_host }}"
        user: "{{ network_username }}"
        password: "{{ network_password }}"
        validate_certs: no
        pool: "{{ pool_name }}"
        partition: "{{ pool_partition }}"
        host: "{{ item }}"
        port: 80
        description: "web server"
        connection_limit: 100
        rate_limit: 50
        ratio: 2
      when: groups.app_hosts is defined
      with_items: "{{ groups.app_hosts }}"

    - name: Add VS on BIG-IP
      bigip_virtual_server:
        server: "{{ ansible_host }}"
        user: "{{ network_username }}"
        password: "{{ network_password }}"
        name: "{{ vs_name }}"
        destination: "{{ interfaces[1].private_ip_address }}"
        port: "{{ vs_port }}"
        pool: "{{ pool_name }}"
        snat: Automap
        validate_certs: False

    - debug: msg="The Virtual Server Address is {{ interfaces[1].public_ip_address }}"
