- hosts: spoke_routers
  connection: network_cli
  gather_facts: no
  tasks:
    - set_fact:
        hub_router: "{{ groups.hub_routers[0] }}"

    - include_role:
        name: network-template
      vars:
        network_template: ipsec-vpn
        vpn_tunnel_ip: "{{ tunnel_ip }}"
        vpn_tunnel_num: "{{ site_number }}"
        vpn_tunnel_src: "{{ interfaces.0.name }}"
        vpn_tunnel_dst: "{{ hostvars[hub_router].ansible_host }}"
        vpn_preshared_key: "{{ tunnel_key }}"

- hosts: hub_routers
  connection: network_cli
  gather_facts: no
  tasks:

    - include_role:
        name: network-template
      vars:
        network_template: ipsec-vpn
        vpn_tunnel_ip: "{{ hostvars[item].tunnel_network | ipaddr(1) }}"
        vpn_tunnel_num: "{{ hostvars[item].site_number }}"
        vpn_tunnel_src: "{{ interfaces.0.name }}"
        vpn_tunnel_dst: "{{ hostvars[item].interfaces.0.public_ip_address }}"
        vpn_preshared_key: "{{ tunnel_key }}"
      with_items: "{{ groups.spoke_routers | default([]) }}"
