---
- hosts: network
  gather_facts: no
  vars:
    site_domain_name: 'example.net'
    network_name_servers:
      - 8.8.8.8
      - 8.8.4.4
    network_domain_search:
      - example.net

  tasks:
    - name: Configure the hostname and domain name
      net_system:
        hostname: "{{ inventory_hostname }}"
        domain_name: "{{ site_domain_name }}"
        domain_search: "{{ network_domain_search | default(omit) }}"
        name_servers: "{{ network_name_servers | default(omit) }}"

    - name: configure host logging
      net_logging:
        dest: host
        name: "{{ site_log_host }}"
        facility: kernel
        level: critical
      when: site_log_host is defined
