---
- name: Setup BGP on the Hub
  hosts: hub_routers
  gather_facts: no
  tasks:
    - include_role:
        name: network-template
      vars:
        network_template: bgp
        bgp_router_id: "{{ interfaces.0.ip | ipaddr('address') }}"
        bgp_asn: "{{ tunnel_asn }}"
        bgp_neighbor_list:
          - ip: "{{ hostvars[item].tunnel_ip | ipaddr('address') }}"
            asn: "{{ tunnel_asn + hostvars[item].site_number|int }}"
      with_items: "{{ groups.spoke_routers | default([]) }}"

- name: Setup BGP on the Spoke
  hosts: spoke_routers
  gather_facts: no
  tasks:
    - include_role:
        name: network-template
      vars:
        network_template: bgp
        bgp_router_id: "{{ tunnel_ip | ipaddr('address') }}"
        bgp_asn: "{{ tunnel_asn + site_number|int }}"
        bgp_neighbor_list:
          - ip: "{{ tunnel_network | ipaddr(1) | ipaddr('address') }}"
            asn: "{{ tunnel_asn }}"
        bgp_network_list:
          - network: "{{ interfaces.0.ip | ipaddr('network') }}"
            mask: "{{ interfaces.0.ip | ipaddr('netmask') }}"
          - network: "{{ interfaces.1.ip | ipaddr('network') }}"
            mask: "{{ interfaces.1.ip | ipaddr('netmask') }}"
          - network: "{{ interfaces.2.ip | ipaddr('network') }}"
            mask: "{{ interfaces.2.ip | ipaddr('netmask') }}"
