---
- hosts: network
  connection: network_cli
  gather_facts: no
  vars:
    minimum_version_list:
      ios: "{{ os_version | default('16.06.01')}}"
      junos: "{{ os_version | default('17.2R1.13')}}"

  tasks:
     - include_role:
         name: network_version
