---
- name: Make sure that we can ping the hosts from the routers
  hosts: routers
  gather_facts: no
  tasks:
    - net_ping:
        dest: "{{ hostvars[item].private_ip_address }}"
        source: loopback0
      with_items: "{{ groups.hosts | default([]) }}"
